export const topics = [
	"Machine Learning",
	"Quantum Computing",
	"Artifical Intelligence",
	"Blockchain",
	"Data Science",
	"Programming",
	"Programming Languages",
	"Dev Ops",
	"Robotic Process Automation",
	"Accessibility in Technology",
	"Edge Computing",
	"Internet of Things (IoT)",
	"Cryptography",
	"Network Security",
	"Big Data Analytics",
	"Accessibility in Technology",
	"Augmented Reality (AR) and Virtual Reality (VR)",
	"Human-Robot Interaction",
	"Neuromorphic Computing"
];